environment:
  nodejs_version: "12"
install:
  # Get the latest stable version of Node.js
  - ps: Install-Product node $env:nodejs_version
  # install modules
  - yarn
test_script:
  # Output useful info for debugging.
  - node --version
  - yarn --version
  # run tests
  - yarn test
build: off
